

stages:
  - docker
  - test
  - build

docker:
  stage: docker
  image: docker
  services:
    - docker:dind
  script:
    - docker build . -t "$CI_REGISTRY_IMAGE/builder"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker push "$CI_REGISTRY_IMAGE/builder"
  interruptible: true
  only:
    refs:
      - main
    changes:
      - Dockerfile

test:
  stage: test
  image: "$CI_REGISTRY_IMAGE/builder"
  interruptible: true
  script:
    - cargo test

build:
  stage: build
  image: "$CI_REGISTRY_IMAGE/builder"
  script:
    - cargo test --release
  interruptible: true
  artifacts:
    paths:
      - target/release/cindy
