

stages:
  - docker
  - test
  - build

docker:
  stage: docker
  image: docker
  services:
    - docker:dind
  script:
    - docker build . -t "$CI_REGISTRY_IMAGE/builder"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker push "$CI_REGISTRY_IMAGE/builder"
  only:
    refs:
      - ci
    changes:
      - Dockerfile
