[package]
name = "cindy-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
hex = "0.4.3"
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1.0.103"
serde_qs = "0.12.0"
thiserror = "1.0.44"

[dev-dependencies]
serde_test = "1.0.175"
