# launch frontend
serve:
    trunk serve

# download tailwind
tailwind:
    mkdir -p target
    curl -sSL https://github.com/tailwindlabs/tailwindcss/releases/download/v3.2.7/tailwindcss-linux-x64 -o ./target/tailwindcss
    chmod +x ./target/tailwindcss

# run syntax formatter
format:
    cargo fmt

# run tests
check:
    cargo fmt --check
    cargo clippy
    cargo test
